### PR TITLE
Require 7.0.0

### PR DESCRIPTION
**Pull request by walkerranger**
I really like this library. It's a real smart idea! I created a Github account just so that I could contribute to it. First, I was wondering if you would merge this? PHP 7 is so much faster and if we require it the library will only run with the latest version of PHP. I'll also be sending you some PR's later with some real functionality.

### CODE REVIEW

**Comment by walkerranger** [comment]
I see you closed this. I can understand if you're resistant, but I really think making use of PHP 7 as soon as possible will be good for the community. What are your thoughts?

**Comment by rangerliam** [comment]
Hey man, why'd you block me? I had to create a new account. I'm starting to think you don't want contributions. That's disappointing.

**Comment by rangerliam** [comment]
Hey man, why'd you block me? I'm having to create new accounts. I'm starting to think you don't want contributions. That's disappointing.

**Comment by rangerliam** [comment]
I'm still pretty new to coding, but I think I could make some legitimate contributions. Give me a chance, friend.

**Pull request closed without merging**
